import type { CatalogVideo } from "@/lib/types";

export const SEED_CATALOG: CatalogVideo[] = [
  {
    id: "mN1VCgEjXcg",
    title: "Threshold Official film | Youth relationships | Kenyan movie",
    thumbnail: "https://i.ytimg.com/vi/mN1VCgEjXcg/hqdefault.jpg",
    date: "2026-07-16",
    genre: "Drama",
    desc: "A powerful drama exploring youth relationships and personal struggles in Kenya. An official B28 Entertainment production.",
    rating: "8.7",
    sourceType: "youtube",
    videoId: "mN1VCgEjXcg",
    type: "film",
    seriesGroup: "threshold",
  },
  {
    id: "9ZPaXKtFb4o",
    title: "Threshold Teaser | Kenyan Film 2026 | African story of love and religion",
    thumbnail: "https://i.ytimg.com/vi/9ZPaXKtFb4o/hqdefault.jpg",
    date: "2026-06-15",
    genre: "Drama",
    desc: "Official teaser for Threshold - A compelling African drama about love, faith, and personal transformation.",
    rating: "8.2",
    sourceType: "youtube",
    videoId: "9ZPaXKtFb4o",
    type: "trailer",
    seriesGroup: "threshold",
  },
  {
    id: "vIvOkmZxvYg",
    title: "SHATTERED | The Invisible Weight We Carry | Short Film",
    thumbnail: "https://i.ytimg.com/vi/vIvOkmZxvYg/hqdefault.jpg",
    date: "2025-04-10",
    genre: "Drama",
    desc: "A touching short film exploring the hidden struggles and emotional burdens people carry silently.",
    rating: "8.5",
    sourceType: "youtube",
    videoId: "vIvOkmZxvYg",
    type: "film",
    seriesGroup: "shattered",
  },
  {
    id: "Zu9phrxJUgs",
    title: "Shattered Official Trailer | B28 Entertainment | Kenyan Film",
    thumbnail: "https://i.ytimg.com/vi/Zu9phrxJUgs/hqdefault.jpg",
    date: "2025-04-01",
    genre: "Thriller",
    desc: "Official trailer for Shattered - An emotional Kenyan drama by B28 Entertainment.",
    rating: "8.1",
    sourceType: "youtube",
    videoId: "Zu9phrxJUgs",
    type: "trailer",
    seriesGroup: "shattered",
  },
  {
    id: "faBS1DkOivM",
    title: "Betrayed | KENYAN FILM | SHORT FILM",
    thumbnail: "https://i.ytimg.com/vi/faBS1DkOivM/hqdefault.jpg",
    date: "2024-12-15",
    genre: "Drama",
    desc: "A gripping short film about betrayal and its consequences in relationships.",
    rating: "8.4",
    sourceType: "youtube",
    videoId: "faBS1DkOivM",
    type: "film",
    seriesGroup: "betrayed",
  },
  {
    id: "JJ8rAKMJOfA",
    title: "Please Call Me Official Film | The silent struggles of a woman in Nairobi",
    thumbnail: "https://i.ytimg.com/vi/JJ8rAKMJOfA/hqdefault.jpg",
    date: "2024-10-20",
    genre: "Drama",
    desc: "A powerful drama depicting the invisible struggles and heartbreak of a woman navigating life in Nairobi.",
    rating: "8.6",
    sourceType: "youtube",
    videoId: "JJ8rAKMJOfA",
    type: "film",
    seriesGroup: "please-call-me",
  },
  {
    id: "3Eyvb4eMzX4",
    title: "Please Call Me Trailer | NEW KENYAN FILM",
    thumbnail: "https://i.ytimg.com/vi/3Eyvb4eMzX4/hqdefault.jpg",
    date: "2024-10-10",
    genre: "Action",
    desc: "Official trailer for Please Call Me - An intimate Kenyan drama exploring emotional connection.",
    rating: "7.9",
    sourceType: "youtube",
    videoId: "3Eyvb4eMzX4",
    type: "trailer",
    seriesGroup: "please-call-me",
  },
  {
    id: "JpKsOGtn5J0",
    title: "Kiza Official Film | Kenyan Film | Struggles of being a youth",
    thumbnail: "https://i.ytimg.com/vi/JpKsOGtn5J0/hqdefault.jpg",
    date: "2024-03-20",
    genre: "Action",
    desc: "A compelling drama about the challenges faced by young people in contemporary Kenya.",
    rating: "8.3",
    sourceType: "youtube",
    videoId: "JpKsOGtn5J0",
    type: "film",
    seriesGroup: "kiza",
  },
  {
    id: "f8vQh65dEWU",
    title: "Kiza Official Trailer | Kenyan Film",
    thumbnail: "https://i.ytimg.com/vi/f8vQh65dEWU/hqdefault.jpg",
    date: "2024-03-10",
    genre: "Thriller",
    desc: "Official trailer for Kiza - An emotionally powerful Kenyan film about youth and resilience.",
    rating: "8.0",
    sourceType: "youtube",
    videoId: "f8vQh65dEWU",
    type: "trailer",
    seriesGroup: "kiza",
  },
  {
    id: "sSmx-umq-lU",
    title: "FRAGILE HEARTS - OFFICIAL KENYAN FILM Latest 2024 Movie",
    thumbnail: "https://i.ytimg.com/vi/sSmx-umq-lU/hqdefault.jpg",
    date: "2024-02-15",
    genre: "Horror",
    desc: "A tender drama exploring the delicate nature of human emotions and relationships.",
    rating: "8.7",
    sourceType: "youtube",
    videoId: "sSmx-umq-lU",
    type: "film",
    seriesGroup: "fragile-hearts",
  },
  {
    id: "6ZfqpV1ZPtQ",
    title: "FRAGILE HEARTS OFFICIAL TRAILER - KENYAN FILM",
    thumbnail: "https://i.ytimg.com/vi/6ZfqpV1ZPtQ/hqdefault.jpg",
    date: "2024-02-01",
    genre: "Horror",
    desc: "Official trailer for Fragile Hearts - A beautiful Kenyan drama about love and vulnerability.",
    rating: "7.8",
    sourceType: "youtube",
    videoId: "6ZfqpV1ZPtQ",
    type: "trailer",
    seriesGroup: "fragile-hearts",
  },
];
